language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/CoreResourceAccessMonitor
  - secure: mcujpGYyIulXAjNIFLvItSwjwuJ1krI8FDoiJ8xSJp0ZbSzkuDteZP0/Y5AuycsJUzZBpV6TXyzO1y6faxIS73d4QEwIOfgnuv89nOcNswMEJYxkdpTS6OQvpt2oBtWqCu8jIHU15BVe6w1mh7gRlaMnhCiv7bncASWE8OVN3RWjXKMCXoPNJQObRHS2670Dbq/nh+nyaFTebYopD2vNByG3Hfo1d5zQYIHWJ7O0153JYw7O4KB4341vYB8N7f+siv+x8sXXlgKBfrnRWrccjyO7blrJFOExMKu00b9NooLpFSXrbjkQ0QzWcBjv8cMXtA1cjyHmZvy8p6NX2njaWEOQLSmhB9bVk9O2e3ybkPnHlCLf2j7zGdIqtviASMMf4ru2k+b0LxBRYHZk/Nld3Gj2wL5nlFfHJL7U+jpyiICLd6sMfhYg8zH0OJfvmLkeSsOxIWvsHtQIeoRbIc6/Ixh8Aec/QNJYJ7s9fiJcl8dxPdNCznCy5LYbsV8mdXGyOQwtzrP6iBzbtWRVxckQyr/JUT+la1J1IFCIE/xEpZIoQ+wvDasdX31ukHHFIq2ViCHJ8tgpawy4LvkFunj3XYfVzEMva3WSIM9+j2l66G4hny19RB5n1vY1Sz7JipebrFSHePrl0M63PhZ01JFhf1fVbA+BRVzJLWJv9xi8qZ0=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
